import { describe, expect, it } from "vitest";
import { getMissionAuthoritativeClaimPlan, getMissionServerCycleKey } from "@/lib/missionAuthoritativeClaims";
import type { Mission } from "@/lib/types";

const baseMission: Mission = {
  id: "d_adv_2",
  kind: "daily",
  name: "Adventurer",
  description: "Clear 2 adventure levels",
  goal: 2,
  metric: "adventure_levels_cleared",
  rewards: { gold: 150 },
};

describe("mission authoritative claims", () => {
  it("allows Adventure missions because their progress is generated by authoritative Adventure events", () => {
    expect(getMissionAuthoritativeClaimPlan(baseMission, new Date("2026-05-12T10:20:00.000Z"))).toEqual({
      ok: true,
      cycleKey: "daily:2026-05-12",
    });
  });

  it("allows hero upgrade missions because hero progression is now generated by server operations", () => {
    expect(
      getMissionAuthoritativeClaimPlan({
        ...baseMission,
        id: "d_upgrade_1",
        metric: "heroes_upgraded",
      }, new Date("2026-05-12T10:20:00.000Z")),
    ).toEqual({ ok: true, cycleKey: "daily:2026-05-12" });
  });

  it("allows all current mission metrics that have server-side progress sources", () => {
    const metrics: Mission["metric"][] = [
      "battles_won",
      "adventure_levels_cleared",
      "arena_battles",
      "heroes_upgraded",
      "events_played",
    ];

    for (const metric of metrics) {
      expect(
        getMissionAuthoritativeClaimPlan({
          ...baseMission,
          metric,
        }, new Date("2026-05-12T10:20:00.000Z")),
      ).toEqual({ ok: true, cycleKey: "daily:2026-05-12" });
    }
  });

  it("uses ISO week keys for weekly server cycles", () => {
    expect(getMissionServerCycleKey({ kind: "weekly" }, new Date("2026-05-12T10:20:00.000Z"))).toBe("weekly:2026-20");
  });
});
