import { describe, expect, it } from "vitest";
import { getMissionAuthoritativeClaimPlan, getMissionServerCycleKey } from "@/lib/missionAuthoritativeClaims";
import type { Mission } from "@/lib/types";

const baseMission: Mission = {
  id: "d_adv_2",
  kind: "daily",
  name: "Adventurer",
  description: "Clear 2 adventure levels",
  goal: 2,
  metric: "adventure_levels_cleared",
  rewards: { gold: 150 },
};

describe("mission authoritative claims", () => {
  it("allows Adventure missions because their progress is generated by authoritative Adventure events", () => {
    expect(getMissionAuthoritativeClaimPlan(baseMission, new Date("2026-05-12T10:20:00.000Z"))).toEqual({
      ok: true,
      cycleKey: "daily:2026-05-12",
    });
  });

  it("keeps hero upgrade missions local until hero progression has its own server operation", () => {
    expect(
      getMissionAuthoritativeClaimPlan({
        ...baseMission,
        id: "d_upgrade_1",
        metric: "heroes_upgraded",
      }),
    ).toEqual({ ok: false, reason: "unsupported_metric" });
  });

  it("uses ISO week keys for weekly server cycles", () => {
    expect(getMissionServerCycleKey({ kind: "weekly" }, new Date("2026-05-12T10:20:00.000Z"))).toBe("weekly:2026-20");
  });
});
