import { getHero } from "@/data/heroes";
import { getLeader } from "@/data/leaders";
import type {
  FrontlineCardDef,
  FrontlineHeroDef,
  FrontlineLeaderDef,
  FrontlinePreset,
  FrontlineSupportDef,
} from "./types";

const hero = (heroId: string) => getHero(heroId);
const leader = (leaderId: string) => getLeader(leaderId);

export const FRONTLINE_LANES = ["left", "center", "right"] as const;

export const FRONTLINE_LEADERS: FrontlineLeaderDef[] = [
  {
    id: "leader_aurora",
    name: leader("leader_aurora").name,
    title: leader("leader_aurora").title,
    factionTone: "dawn",
    coreHp: 25,
    power: {
      name: "Solar Lance",
      description: "Blast a chosen front and steady your core.",
      cost: 2,
      cooldown: 2,
      effect: { type: "beam", damage: 6, healCore: 2 },
    },
  },
  {
    id: "leader_morrow",
    name: leader("leader_morrow").name,
    title: leader("leader_morrow").title,
    factionTone: "shadow",
    coreHp: 24,
    power: {
      name: "Night Command",
      description: "All allied heroes surge for the current clash.",
      cost: 2,
      cooldown: 2,
      effect: { type: "rally", atk: 2, shield: 2 },
    },
  },
];

export const FRONTLINE_LEADER_BY_ID = Object.fromEntries(
  FRONTLINE_LEADERS.map((entry) => [entry.id, entry]),
);

export const FRONTLINE_HEROES: FrontlineHeroDef[] = [
  {
    heroId: "bran",
    name: hero("bran").name,
    role: "Anchor tank",
    family: "hero",
    tier: 3,
    rarity: hero("bran").rarity,
    maxHp: 22,
    atk: 4,
    def: 3,
    speed: 2,
    trait: { type: "bulwark", shield: 3 },
  },
  {
    heroId: "kara",
    name: hero("kara").name,
    role: "Blade striker",
    family: "hero",
    tier: 3,
    rarity: hero("kara").rarity,
    maxHp: 16,
    atk: 7,
    def: 1,
    speed: 5,
    trait: { type: "flurry", atk: 2 },
  },
  {
    heroId: "vex",
    name: hero("vex").name,
    role: "Breach archer",
    family: "hero",
    tier: 3,
    rarity: hero("vex").rarity,
    maxHp: 14,
    atk: 6,
    def: 1,
    speed: 4,
    trait: { type: "breach", extra: 1 },
  },
  {
    heroId: "mira",
    name: hero("mira").name,
    role: "Field healer",
    family: "hero",
    tier: 3,
    rarity: hero("mira").rarity,
    maxHp: 18,
    atk: 4,
    def: 2,
    speed: 3,
    trait: { type: "mend", heal: 3 },
  },
  {
    heroId: "drak",
    name: hero("drak").name,
    role: "Shadow finisher",
    family: "hero",
    tier: 3,
    rarity: hero("drak").rarity,
    maxHp: 15,
    atk: 8,
    def: 1,
    speed: 6,
    trait: { type: "ambush", bonusVsWounded: 2 },
  },
  {
    heroId: "tovi",
    name: hero("tovi").name,
    role: "War chanter",
    family: "hero",
    tier: 3,
    rarity: hero("tovi").rarity,
    maxHp: 17,
    atk: 4,
    def: 2,
    speed: 3,
    trait: { type: "chant", atkAura: 1 },
  },
];

export const FRONTLINE_HERO_BY_ID = Object.fromEntries(
  FRONTLINE_HEROES.map((entry) => [entry.heroId, entry]),
);

export const FRONTLINE_ENEMIES: FrontlineHeroDef[] = [
  {
    heroId: "enemy_bone_archer",
    name: "Bonechitter Archer",
    role: "Skirmish archer",
    family: "enemy",
    tier: 1,
    rarity: "common",
    maxHp: 12,
    atk: 5,
    def: 0,
    speed: 6,
    trait: { type: "breach", extra: 1 },
  },
  {
    heroId: "enemy_rotmaw",
    name: "Rotmaw Ghoul",
    role: "Venom bruiser",
    family: "enemy",
    tier: 1,
    rarity: "common",
    maxHp: 17,
    atk: 6,
    def: 1,
    speed: 4,
    trait: { type: "venom", damage: 2 },
  },
  {
    heroId: "enemy_void_acolyte",
    name: "Void Acolyte",
    role: "Backline chanter",
    family: "enemy",
    tier: 2,
    rarity: "rare",
    maxHp: 15,
    atk: 4,
    def: 1,
    speed: 3,
    trait: { type: "chant", atkAura: 1 },
  },
  {
    heroId: "enemy_plague_troll",
    name: "Plaguebound Troll",
    role: "Slow regenerator",
    family: "enemy",
    tier: 2,
    rarity: "rare",
    maxHp: 25,
    atk: 5,
    def: 3,
    speed: 1,
    trait: { type: "mend", heal: 2 },
  },
  {
    heroId: "enemy_blood_duelist",
    name: "Bloodcourt Duelist",
    role: "Lifesteal duelist",
    family: "enemy",
    tier: 3,
    rarity: "epic",
    maxHp: 16,
    atk: 7,
    def: 1,
    speed: 6,
    trait: { type: "lifesteal", heal: 3 },
  },
  {
    heroId: "enemy_ember_ogre",
    name: "Emberhorn Ogre",
    role: "Siege brute",
    family: "enemy",
    tier: 4,
    rarity: "epic",
    maxHp: 30,
    atk: 8,
    def: 4,
    speed: 1,
    trait: { type: "none" },
  },
];

export const FRONTLINE_ENEMY_BY_ID = Object.fromEntries(
  FRONTLINE_ENEMIES.map((entry) => [entry.heroId, entry]),
);

export const FRONTLINE_UNIT_BY_ID = {
  ...FRONTLINE_HERO_BY_ID,
  ...FRONTLINE_ENEMY_BY_ID,
};

export const FRONTLINE_SUPPORTS: FrontlineSupportDef[] = [
  {
    id: "wolf",
    name: "Pack Wolf",
    maxHp: 8,
    atk: 3,
    duration: 2,
    intercepts: true,
    effect: { type: "strike", damage: 2 },
  },
  {
    id: "barrier",
    name: "Arcane Barrier",
    maxHp: 10,
    atk: 0,
    duration: 2,
    intercepts: true,
    effect: { type: "shield", amount: 2 },
  },
  {
    id: "totem",
    name: "War Totem",
    maxHp: 6,
    atk: 2,
    duration: 2,
    intercepts: false,
    effect: { type: "mark", damage: 2 },
  },
  {
    id: "bone_imp",
    name: "Bone Imp",
    maxHp: 6,
    atk: 3,
    duration: 2,
    intercepts: true,
    effect: { type: "strike", damage: 1 },
  },
  {
    id: "rot_ward",
    name: "Rot Ward",
    maxHp: 9,
    atk: 1,
    duration: 2,
    intercepts: true,
    effect: { type: "mark", damage: 2 },
  },
  {
    id: "void_eye",
    name: "Void Eye",
    maxHp: 7,
    atk: 2,
    duration: 2,
    intercepts: false,
    effect: { type: "mark", damage: 3 },
  },
];

export const FRONTLINE_SUPPORT_BY_ID = Object.fromEntries(
  FRONTLINE_SUPPORTS.map((entry) => [entry.id, entry]),
);

export const FRONTLINE_PLAYER_CARDS: FrontlineCardDef[] = [
  {
    id: "order_guard_wall",
    kind: "order",
    name: "Guard Wall",
    cost: 1,
    description: "Target ally front gains 4 shield and 1 attack this clash.",
    target: "ally_front",
    effect: { type: "hero_strike", atk: 1, shield: 4 },
  },
  {
    id: "order_twin_slash",
    kind: "order",
    name: "Twin Slash",
    cost: 1,
    description: "A sharp order that gives a hero 3 attack and first strike.",
    target: "ally_front",
    effect: { type: "hero_strike", atk: 3, strikeFirst: true },
  },
  {
    id: "order_shadow_dive",
    kind: "order",
    name: "Shadow Dive",
    cost: 2,
    description: "Hit the chosen enemy front before clash and threaten a breach.",
    target: "enemy_front",
    effect: { type: "execute_front", damage: 5, bonusOpenCore: 2 },
  },
  {
    id: "order_focus_fire",
    kind: "order",
    name: "Focus Fire",
    cost: 2,
    description: "Blast a front for 5 before normal combat.",
    target: "enemy_front",
    effect: { type: "front_shot", damage: 5 },
  },
  {
    id: "tactic_battle_hymn",
    kind: "tactic",
    name: "Battle Hymn",
    cost: 1,
    description: "All allied heroes gain 2 attack this turn.",
    target: "none",
    effect: { type: "rally", atk: 2 },
  },
  {
    id: "tactic_sanctuary",
    kind: "tactic",
    name: "Sanctuary",
    cost: 2,
    description: "Heal one front and patch the core a little.",
    target: "ally_front",
    effect: { type: "heal_front", heal: 6, coreHeal: 2 },
  },
  {
    id: "tactic_smokescreen",
    kind: "tactic",
    name: "Smokescreen",
    cost: 1,
    description: "Stun a front for the next clash.",
    target: "enemy_front",
    effect: { type: "stun_front", turns: 1 },
  },
  {
    id: "tactic_core_burst",
    kind: "tactic",
    name: "Core Burst",
    cost: 3,
    description: "Heavy strike that gets nastier on an open front.",
    target: "enemy_front",
    effect: { type: "execute_front", damage: 7, bonusOpenCore: 3 },
  },
  {
    id: "summon_wolf",
    kind: "summon",
    name: "Wolf Pack",
    cost: 1,
    description: "Summon a temporary wolf to intercept a front. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "wolf" },
    usesPerBattle: 1,
  },
  {
    id: "summon_barrier",
    kind: "summon",
    name: "Arcane Barrier",
    cost: 1,
    description: "Raise a barrier that absorbs the next push. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "barrier" },
    usesPerBattle: 1,
  },
  {
    id: "summon_totem",
    kind: "summon",
    name: "War Totem",
    cost: 2,
    description: "Plant a totem that adds chip pressure during clash. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "totem" },
    usesPerBattle: 1,
  },
];

export const FRONTLINE_ENEMY_CARDS: FrontlineCardDef[] = [
  {
    id: "enemy_order_bone_arrow",
    kind: "order",
    name: "Bone Arrow",
    cost: 1,
    description: "A fast shot into the weakest front.",
    target: "enemy_front",
    effect: { type: "front_shot", damage: 4 },
  },
  {
    id: "enemy_order_crushing_swing",
    kind: "order",
    name: "Crushing Swing",
    cost: 2,
    description: "A slow brute front gains heavy attack for the clash.",
    target: "ally_front",
    effect: { type: "hero_strike", atk: 4 },
  },
  {
    id: "enemy_order_infernal_cleave",
    kind: "order",
    name: "Infernal Cleave",
    cost: 3,
    description: "A decisive strike that punishes an open front.",
    target: "enemy_front",
    effect: { type: "execute_front", damage: 8, bonusOpenCore: 3 },
  },
  {
    id: "enemy_tactic_plague_spit",
    kind: "tactic",
    name: "Plague Spit",
    cost: 1,
    description: "Stun a pressured enemy front.",
    target: "enemy_front",
    effect: { type: "stun_front", turns: 1 },
  },
  {
    id: "enemy_tactic_blood_rite",
    kind: "tactic",
    name: "Blood Rite",
    cost: 2,
    description: "Patch a wounded monster and steady the core.",
    target: "ally_front",
    effect: { type: "heal_front", heal: 5, coreHeal: 1 },
  },
  {
    id: "enemy_tactic_war_howl",
    kind: "tactic",
    name: "War Howl",
    cost: 1,
    description: "All enemy units gain attack for this clash.",
    target: "none",
    effect: { type: "rally", atk: 1 },
  },
  {
    id: "enemy_summon_bone_imp",
    kind: "summon",
    name: "Bone Imp",
    cost: 1,
    description: "A disposable imp intercepts a front. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "bone_imp" },
    usesPerBattle: 1,
  },
  {
    id: "enemy_summon_void_eye",
    kind: "summon",
    name: "Void Eye",
    cost: 2,
    description: "A floating eye adds magical chip pressure. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "void_eye" },
    usesPerBattle: 1,
  },
];

export const FRONTLINE_CARDS: FrontlineCardDef[] = [
  ...FRONTLINE_PLAYER_CARDS,
  ...FRONTLINE_ENEMY_CARDS,
];

export const FRONTLINE_CARD_BY_ID = Object.fromEntries(
  FRONTLINE_CARDS.map((entry) => [entry.id, entry]),
);

export const FRONTLINE_STARTER_DECK = [
  "order_guard_wall",
  "order_twin_slash",
  "order_focus_fire",
  "tactic_battle_hymn",
  "tactic_sanctuary",
  "tactic_smokescreen",
  "summon_wolf",
  "summon_barrier",
];

export const FRONTLINE_CARD_POOL = FRONTLINE_PLAYER_CARDS.map((card) => card.id);

export const FRONTLINE_PRESETS: FrontlinePreset[] = [
  {
    id: "bonewood_scouts",
    name: "Bonewood Scouts",
    leaderId: "leader_morrow",
    squad: ["enemy_bone_archer", "enemy_rotmaw", "enemy_void_acolyte"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_bone_arrow",
      "enemy_tactic_war_howl",
      "enemy_summon_bone_imp",
      "enemy_summon_bone_imp",
      "enemy_tactic_plague_spit",
    ],
    rewardSeed: { gold: 110, dust: 10, gems: 1, accountXp: 5 },
  },
  {
    id: "bonewood_raiders",
    name: "Bonewood Raiders",
    leaderId: "leader_morrow",
    squad: ["enemy_bone_archer", "enemy_rotmaw", "enemy_void_acolyte"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_bone_arrow",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_summon_bone_imp",
      "enemy_summon_bone_imp",
      "enemy_summon_void_eye",
      "enemy_tactic_blood_rite",
    ],
    rewardSeed: { gold: 135, dust: 15, gems: 2, accountXp: 7 },
  },
  {
    id: "rotwood_pack",
    name: "Rotwood Pack",
    leaderId: "leader_morrow",
    squad: ["enemy_rotmaw", "enemy_plague_troll", "enemy_bone_archer"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_crushing_swing",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_summon_bone_imp",
      "enemy_summon_void_eye",
    ],
    rewardSeed: { gold: 145, dust: 16, gems: 2, accountXp: 8 },
  },
  {
    id: "plague_pack",
    name: "Plague Pack",
    leaderId: "leader_morrow",
    squad: ["enemy_plague_troll", "enemy_rotmaw", "enemy_bone_archer"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
      "enemy_tactic_plague_spit",
      "enemy_tactic_plague_spit",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_summon_bone_imp",
      "enemy_summon_void_eye",
    ],
    rewardSeed: { gold: 155, dust: 17, gems: 3, accountXp: 8 },
  },
  {
    id: "bloodcourt_ambush",
    name: "Bloodcourt Ambush",
    leaderId: "leader_morrow",
    squad: ["enemy_blood_duelist", "enemy_void_acolyte", "enemy_plague_troll"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
      "enemy_summon_bone_imp",
    ],
    rewardSeed: { gold: 165, dust: 18, gems: 3, accountXp: 9 },
  },
  {
    id: "ember_vanguard",
    name: "Ember Vanguard",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_bone_archer", "enemy_blood_duelist"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_order_bone_arrow",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
      "enemy_summon_bone_imp",
    ],
    rewardSeed: { gold: 175, dust: 19, gems: 4, accountXp: 10 },
  },
  {
    id: "ember_court",
    name: "Ember Court",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_void_acolyte"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_order_bone_arrow",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
    ],
    rewardSeed: { gold: 180, dust: 20, gems: 4, accountXp: 10 },
  },
  {
    id: "eclipse_court",
    name: "Eclipse Court",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_void_acolyte"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_tactic_plague_spit",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 190, dust: 22, gems: 5, accountXp: 12 },
  },
  {
    id: "the_eclipse",
    name: "The Eclipse",
    leaderId: "leader_morrow",
    squad: ["enemy_void_acolyte", "enemy_blood_duelist", "enemy_ember_ogre"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
      "enemy_summon_void_eye",
      "enemy_tactic_blood_rite",
    ],
    rewardSeed: { gold: 200, dust: 24, gems: 6, accountXp: 13 },
    bossId: "the_eclipse",
  },
  {
    id: "ashen_warband",
    name: "Ashen Warband",
    leaderId: "leader_morrow",
    squad: ["enemy_blood_duelist", "enemy_rotmaw", "enemy_plague_troll"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
      "enemy_tactic_blood_rite",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_summon_bone_imp",
      "enemy_summon_void_eye",
      "enemy_order_infernal_cleave",
    ],
    rewardSeed: { gold: 205, dust: 24, gems: 5, accountXp: 12 },
  },
  {
    id: "ogre_siege_line",
    name: "Ogre Siege Line",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_plague_troll", "enemy_rotmaw"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_tactic_blood_rite",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_bone_imp",
    ],
    rewardSeed: { gold: 220, dust: 26, gems: 5, accountXp: 13 },
  },
  {
    id: "void_eclipse_guard",
    name: "Void Eclipse Guard",
    leaderId: "leader_morrow",
    squad: ["enemy_void_acolyte", "enemy_blood_duelist", "enemy_ember_ogre"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 235, dust: 28, gems: 6, accountXp: 14 },
  },
  {
    id: "crown_of_ashes",
    name: "Crown of Ashes",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_plague_troll"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_order_infernal_cleave",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_tactic_plague_spit",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
    ],
    rewardSeed: { gold: 260, dust: 32, gems: 8, accountXp: 16 },
  },
];

export const FRONTLINE_PRESET_BY_ID = Object.fromEntries(
  FRONTLINE_PRESETS.map((entry) => [entry.id, entry]),
);
