import type { FrontlinePreset } from "./types";

export const FRONTLINE_PRESETS: FrontlinePreset[] = [
  {
    id: "bonewood_scouts",
    name: "Bonewood Scouts",
    leaderId: "leader_morrow",
    squad: ["enemy_bone_archer", "enemy_rotmaw", "enemy_void_acolyte"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_bone_arrow",
      "enemy_tactic_war_howl",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
    ],
    rewardSeed: { gold: 110, dust: 10, gems: 1, accountXp: 5 },
  },
  {
    id: "bonewood_raiders",
    name: "Bonewood Raiders",
    leaderId: "leader_morrow",
    squad: ["enemy_bone_archer", "enemy_rotmaw", "enemy_void_acolyte"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_bone_arrow",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_blood_rite",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 135, dust: 15, gems: 2, accountXp: 7 },
  },
  {
    id: "rotwood_pack",
    name: "Rotwood Pack",
    leaderId: "leader_morrow",
    squad: ["enemy_rotmaw", "enemy_plague_troll", "enemy_bone_archer"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_crushing_swing",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_order_bone_arrow",
      "enemy_tactic_war_howl",
    ],
    rewardSeed: { gold: 145, dust: 16, gems: 2, accountXp: 8 },
  },
  {
    id: "plague_pack",
    name: "Plague Pack",
    leaderId: "leader_morrow",
    squad: ["enemy_plague_troll", "enemy_rotmaw", "enemy_bone_archer"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
      "enemy_tactic_plague_spit",
      "enemy_tactic_plague_spit",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 155, dust: 17, gems: 3, accountXp: 8 },
  },
  {
    id: "bloodcourt_ambush",
    name: "Bloodcourt Ambush",
    leaderId: "leader_morrow",
    squad: ["enemy_blood_duelist", "enemy_void_acolyte", "enemy_plague_troll"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_order_infernal_cleave",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
    ],
    rewardSeed: { gold: 165, dust: 18, gems: 3, accountXp: 9 },
  },
  {
    id: "ember_vanguard",
    name: "Ember Vanguard",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_bone_archer", "enemy_blood_duelist"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_order_bone_arrow",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
      "enemy_summon_bone_imp",
    ],
    rewardSeed: { gold: 175, dust: 19, gems: 4, accountXp: 10 },
  },
  {
    id: "ember_court",
    name: "Ember Court",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_void_acolyte"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_order_bone_arrow",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
    ],
    rewardSeed: { gold: 180, dust: 20, gems: 4, accountXp: 10 },
  },
  {
    id: "eclipse_court",
    name: "Eclipse Court",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_void_acolyte"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_tactic_plague_spit",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 190, dust: 22, gems: 5, accountXp: 12 },
  },
  {
    id: "the_eclipse",
    name: "The Eclipse",
    leaderId: "leader_morrow",
    squad: ["enemy_void_acolyte", "enemy_blood_duelist", "enemy_ember_ogre"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_summon_void_eye_boss",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_order_infernal_cleave",
    ],
    rewardSeed: { gold: 200, dust: 24, gems: 6, accountXp: 13 },
    bossId: "the_eclipse",
  },
  {
    id: "ashen_warband",
    name: "Ashen Warband",
    leaderId: "leader_morrow",
    squad: ["enemy_blood_duelist", "enemy_rotmaw", "enemy_plague_troll"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
      "enemy_tactic_blood_rite",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_summon_bone_imp",
      "enemy_summon_void_eye",
      "enemy_order_infernal_cleave",
    ],
    rewardSeed: { gold: 205, dust: 24, gems: 5, accountXp: 12 },
  },
  {
    id: "ogre_siege_line",
    name: "Ogre Siege Line",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_plague_troll", "enemy_rotmaw"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_tactic_blood_rite",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_bone_imp",
    ],
    rewardSeed: { gold: 220, dust: 26, gems: 5, accountXp: 13 },
  },
  {
    id: "void_eclipse_guard",
    name: "Void Eclipse Guard",
    leaderId: "leader_morrow",
    squad: ["enemy_void_acolyte", "enemy_blood_duelist", "enemy_ember_ogre"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 235, dust: 28, gems: 6, accountXp: 14 },
  },
  {
    id: "crown_of_ashes",
    name: "Crown of Ashes",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_plague_troll"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_order_infernal_cleave",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_tactic_plague_spit",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
    ],
    rewardSeed: { gold: 260, dust: 32, gems: 8, accountXp: 16 },
  },
];

export const FRONTLINE_PRESET_BY_ID = Object.fromEntries(
  FRONTLINE_PRESETS.map((entry) => [entry.id, entry]),
);
