import type { FrontlineCardDef } from "./types";

export const FRONTLINE_PLAYER_CARDS: FrontlineCardDef[] = [
  {
    id: "order_guard_wall",
    kind: "order",
    name: "Guard Wall",
    cost: 1,
    description: "Target ally front gains 4 shield and 1 attack this clash.",
    target: "ally_front",
    effect: { type: "hero_strike", atk: 1, shield: 4 },
  },
  {
    id: "order_twin_slash",
    kind: "order",
    name: "Twin Slash",
    cost: 1,
    description: "A sharp order that gives a hero 3 attack and first strike.",
    target: "ally_front",
    effect: { type: "hero_strike", atk: 3, strikeFirst: true },
  },
  {
    id: "order_shadow_dive",
    kind: "order",
    name: "Shadow Dive",
    cost: 2,
    description: "Hit the chosen enemy front before clash and threaten a breach.",
    target: "enemy_front",
    effect: { type: "execute_front", damage: 5, bonusOpenCore: 2 },
  },
  {
    id: "order_focus_fire",
    kind: "order",
    name: "Focus Fire",
    cost: 2,
    description: "Blast a front for 5 before normal combat.",
    target: "enemy_front",
    effect: { type: "front_shot", damage: 5 },
  },
  {
    id: "tactic_battle_hymn",
    kind: "tactic",
    name: "Battle Hymn",
    cost: 1,
    description: "All allied heroes gain 2 attack this turn.",
    target: "none",
    effect: { type: "rally", atk: 2 },
  },
  {
    id: "tactic_sanctuary",
    kind: "tactic",
    name: "Sanctuary",
    cost: 2,
    description: "Heal one front and patch the core a little.",
    target: "ally_front",
    effect: { type: "heal_front", heal: 6, coreHeal: 2 },
  },
  {
    id: "tactic_smokescreen",
    kind: "tactic",
    name: "Smokescreen",
    cost: 1,
    description: "Stun a front for the next clash.",
    target: "enemy_front",
    effect: { type: "stun_front", turns: 1 },
  },
  {
    id: "tactic_core_burst",
    kind: "tactic",
    name: "Core Burst",
    cost: 3,
    description: "Heavy strike that gets nastier on an open front.",
    target: "enemy_front",
    effect: { type: "execute_front", damage: 7, bonusOpenCore: 3 },
  },
  {
    id: "guard_break",
    kind: "order",
    name: "Guard Break",
    cost: 1,
    description: "Crack an enemy front for 3 damage and punish an exposed core.",
    target: "enemy_front",
    effect: { type: "execute_front", damage: 3, bonusOpenCore: 1 },
  },
  {
    id: "quick_step",
    kind: "order",
    name: "Quick Step",
    cost: 1,
    description: "Give an ally front 2 attack and first strike this clash.",
    target: "ally_front",
    effect: { type: "hero_strike", atk: 2, strikeFirst: true },
  },
  {
    id: "iron_skin",
    kind: "tactic",
    name: "Iron Skin",
    cost: 1,
    description: "Fortify an ally front with 5 shield before the clash.",
    target: "ally_front",
    effect: { type: "hero_strike", atk: 0, shield: 5 },
  },
  {
    id: "piercing_shot",
    kind: "order",
    name: "Piercing Shot",
    cost: 2,
    description: "Pierce an enemy front for 6 direct damage.",
    target: "enemy_front",
    effect: { type: "front_shot", damage: 6 },
  },
  {
    id: "dark_bolt",
    kind: "tactic",
    name: "Dark Bolt",
    cost: 2,
    description: "Strike an enemy front for 4 damage before the clash.",
    target: "enemy_front",
    effect: { type: "front_shot", damage: 4 },
  },
  {
    id: "war_drums",
    kind: "tactic",
    name: "War Drums",
    cost: 2,
    description: "All allied heroes gain 1 attack and 2 shield this turn.",
    target: "none",
    effect: { type: "rally", atk: 1, shield: 2 },
  },
  {
    id: "summon_wolf",
    kind: "summon",
    name: "Wolf Pack",
    cost: 1,
    description: "Summon a temporary wolf to intercept a front. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "wolf" },
    usesPerBattle: 1,
  },
  {
    id: "summon_barrier",
    kind: "summon",
    name: "Arcane Barrier",
    cost: 1,
    description: "Raise a barrier that absorbs the next push. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "barrier" },
    usesPerBattle: 1,
  },
  {
    id: "summon_totem",
    kind: "summon",
    name: "War Totem",
    cost: 2,
    description: "Plant a totem that adds chip pressure during clash. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "totem" },
    usesPerBattle: 1,
  },
];

export const FRONTLINE_ENEMY_CARDS: FrontlineCardDef[] = [
  {
    id: "enemy_order_bone_arrow",
    kind: "order",
    name: "Bone Arrow",
    cost: 1,
    description: "A fast shot into the weakest front.",
    target: "enemy_front",
    effect: { type: "front_shot", damage: 4 },
  },
  {
    id: "enemy_order_crushing_swing",
    kind: "order",
    name: "Crushing Swing",
    cost: 2,
    description: "A slow brute front gains heavy attack for the clash.",
    target: "ally_front",
    effect: { type: "hero_strike", atk: 4 },
  },
  {
    id: "enemy_order_infernal_cleave",
    kind: "order",
    name: "Infernal Cleave",
    cost: 3,
    description: "A decisive strike that punishes an open front.",
    target: "enemy_front",
    effect: { type: "execute_front", damage: 8, bonusOpenCore: 3 },
  },
  {
    id: "enemy_tactic_plague_spit",
    kind: "tactic",
    name: "Plague Spit",
    cost: 1,
    description: "Stun a pressured enemy front.",
    target: "enemy_front",
    effect: { type: "stun_front", turns: 1 },
  },
  {
    id: "enemy_tactic_blood_rite",
    kind: "tactic",
    name: "Blood Rite",
    cost: 2,
    description: "Patch a wounded monster and steady the core.",
    target: "ally_front",
    effect: { type: "heal_front", heal: 5, coreHeal: 1 },
  },
  {
    id: "enemy_tactic_war_howl",
    kind: "tactic",
    name: "War Howl",
    cost: 1,
    description: "All enemy units gain attack for this clash.",
    target: "none",
    effect: { type: "rally", atk: 1 },
  },
  {
    id: "enemy_summon_bone_imp",
    kind: "summon",
    name: "Bone Imp",
    cost: 1,
    description: "A disposable imp intercepts a front. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "bone_imp" },
    usesPerBattle: 1,
  },
  {
    id: "enemy_summon_void_eye",
    kind: "summon",
    name: "Void Eye",
    cost: 2,
    description: "A floating eye adds magical chip pressure. One use per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "void_eye" },
    usesPerBattle: 1,
  },
  {
    // Boss-only variant with two uses per battle. Reserved for boss decks
    // (currently the_eclipse). Identical effect, higher cap.
    id: "enemy_summon_void_eye_boss",
    kind: "summon",
    name: "Void Eye",
    cost: 2,
    description: "A floating eye adds magical chip pressure. Two uses per battle.",
    target: "ally_front",
    effect: { type: "summon", supportId: "void_eye" },
    usesPerBattle: 2,
  },
];

export const FRONTLINE_CARDS: FrontlineCardDef[] = [
  ...FRONTLINE_PLAYER_CARDS,
  ...FRONTLINE_ENEMY_CARDS,
];

export const FRONTLINE_CARD_BY_ID = Object.fromEntries(
  FRONTLINE_CARDS.map((entry) => [entry.id, entry]),
);

export const FRONTLINE_STARTER_DECK = [
  "order_guard_wall",
  "order_twin_slash",
  "order_focus_fire",
  "tactic_battle_hymn",
  "tactic_sanctuary",
  "tactic_smokescreen",
  "summon_wolf",
  "summon_barrier",
];

export const FRONTLINE_CARD_POOL = FRONTLINE_PLAYER_CARDS.map((card) => card.id);
