import type { FrontlinePreset } from "./types";

export const FRONTLINE_PRESETS: FrontlinePreset[] = [
  {
    id: "bonewood_scouts",
    name: "Bonewood Scouts",
    leaderId: "leader_morrow",
    squad: ["enemy_bone_archer", "enemy_rotmaw", "enemy_void_acolyte"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_bone_arrow",
      "enemy_tactic_war_howl",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
    ],
    rewardSeed: { gold: 110, dust: 10, gems: 1, accountXp: 5 },
  },
  {
    id: "bonewood_raiders",
    name: "Bonewood Raiders",
    leaderId: "leader_morrow",
    squad: ["enemy_bone_archer", "enemy_rotmaw", "enemy_void_acolyte"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_bone_arrow",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_blood_rite",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 135, dust: 15, gems: 2, accountXp: 7 },
  },
  {
    id: "rotwood_pack",
    name: "Rotwood Pack",
    leaderId: "leader_morrow",
    squad: ["enemy_rotmaw", "enemy_plague_troll", "enemy_bone_archer"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_crushing_swing",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_order_bone_arrow",
      "enemy_tactic_war_howl",
    ],
    rewardSeed: { gold: 145, dust: 16, gems: 2, accountXp: 8 },
  },
  {
    id: "plague_pack",
    name: "Plague Pack",
    leaderId: "leader_morrow",
    squad: ["enemy_plague_troll", "enemy_rotmaw", "enemy_bone_archer"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
      "enemy_tactic_plague_spit",
      "enemy_tactic_plague_spit",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 155, dust: 17, gems: 3, accountXp: 8 },
  },
  {
    id: "bloodcourt_ambush",
    name: "Bloodcourt Ambush",
    leaderId: "leader_morrow",
    squad: ["enemy_blood_duelist", "enemy_void_acolyte", "enemy_plague_troll"],
    deck: [
      "enemy_order_bone_arrow",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_order_infernal_cleave",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
    ],
    rewardSeed: { gold: 165, dust: 18, gems: 3, accountXp: 9 },
  },
  {
    id: "ember_vanguard",
    name: "Ember Vanguard",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_bone_archer", "enemy_blood_duelist"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_order_bone_arrow",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
      "enemy_summon_bone_imp",
    ],
    rewardSeed: { gold: 175, dust: 19, gems: 4, accountXp: 10 },
  },
  {
    id: "ember_court",
    name: "Ember Court",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_void_acolyte"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_order_bone_arrow",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
    ],
    rewardSeed: { gold: 180, dust: 20, gems: 4, accountXp: 10 },
  },
  {
    id: "eclipse_court",
    name: "Eclipse Court",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_void_acolyte"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_tactic_plague_spit",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 190, dust: 22, gems: 5, accountXp: 12 },
  },
  {
    id: "the_eclipse",
    name: "The Eclipse",
    leaderId: "leader_morrow",
    squad: ["enemy_void_acolyte", "enemy_blood_duelist", "enemy_ember_ogre"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_tactic_war_howl",
      "enemy_tactic_blood_rite",
      "enemy_summon_void_eye_boss",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_order_infernal_cleave",
    ],
    rewardSeed: { gold: 200, dust: 24, gems: 6, accountXp: 13 },
    bossId: "the_eclipse",
  },
  {
    id: "ashen_warband",
    name: "Ashen Warband",
    leaderId: "leader_morrow",
    squad: ["enemy_blood_duelist", "enemy_rotmaw", "enemy_plague_troll"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
      "enemy_tactic_blood_rite",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_summon_bone_imp",
      "enemy_summon_void_eye",
      "enemy_order_infernal_cleave",
    ],
    rewardSeed: { gold: 205, dust: 24, gems: 5, accountXp: 12 },
  },
  {
    id: "ogre_siege_line",
    name: "Ogre Siege Line",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_plague_troll", "enemy_rotmaw"],
    deck: [
      "enemy_order_crushing_swing",
      "enemy_order_crushing_swing",
      "enemy_order_infernal_cleave",
      "enemy_tactic_blood_rite",
      "enemy_tactic_plague_spit",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_bone_imp",
    ],
    rewardSeed: { gold: 220, dust: 26, gems: 5, accountXp: 13 },
  },
  {
    id: "void_eclipse_guard",
    name: "Void Eclipse Guard",
    leaderId: "leader_morrow",
    squad: ["enemy_void_acolyte", "enemy_blood_duelist", "enemy_ember_ogre"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
      "enemy_tactic_plague_spit",
      "enemy_order_crushing_swing",
      "enemy_order_bone_arrow",
    ],
    rewardSeed: { gold: 235, dust: 28, gems: 6, accountXp: 14 },
  },
  {
    id: "crown_of_ashes",
    name: "Crown of Ashes",
    leaderId: "leader_morrow",
    squad: ["enemy_ember_ogre", "enemy_blood_duelist", "enemy_plague_troll"],
    deck: [
      "enemy_order_infernal_cleave",
      "enemy_order_infernal_cleave",
      "enemy_order_crushing_swing",
      "enemy_tactic_blood_rite",
      "enemy_tactic_war_howl",
      "enemy_tactic_plague_spit",
      "enemy_summon_void_eye",
      "enemy_summon_void_eye",
    ],
    rewardSeed: { gold: 260, dust: 32, gems: 8, accountXp: 16 },
  },
  {
    id: "ladder_bronze_iii_iron_vow",
    name: "Iron Vow",
    leaderId: "leader_aurora",
    squad: ["bran", "vex", "mira"],
    deck: [
      "order_guard_wall",
      "order_focus_fire",
      "tactic_sanctuary",
      "tactic_smokescreen",
      "summon_wolf",
      "summon_barrier",
      "tactic_battle_hymn",
      "order_twin_slash",
    ],
    rewardSeed: { gold: 60, dust: 4, gems: 0, accountXp: 4 },
  },
  {
    id: "ladder_bronze_iii_candle_warden",
    name: "Candle Warden",
    leaderId: "leader_aurora",
    squad: ["bran", "tovi", "mira"],
    deck: [
      "order_guard_wall",
      "order_guard_wall",
      "tactic_sanctuary",
      "tactic_battle_hymn",
      "summon_barrier",
      "summon_wolf",
      "order_focus_fire",
      "tactic_smokescreen",
    ],
    rewardSeed: { gold: 60, dust: 4, gems: 0, accountXp: 4 },
  },
  {
    id: "ladder_bronze_iii_mistbound_recruit",
    name: "Mistbound Recruit",
    leaderId: "leader_morrow",
    squad: ["kara", "vex", "bran"],
    deck: [
      "order_twin_slash",
      "order_focus_fire",
      "order_guard_wall",
      "tactic_smokescreen",
      "summon_wolf",
      "tactic_battle_hymn",
      "summon_barrier",
      "order_focus_fire",
    ],
    rewardSeed: { gold: 60, dust: 4, gems: 0, accountXp: 4 },
  },
  {
    id: "ladder_bronze_ii_ash_squire",
    name: "Ash Squire",
    leaderId: "leader_morrow",
    squad: ["kara", "bran", "vex"],
    deck: [
      "order_twin_slash",
      "order_focus_fire",
      "tactic_battle_hymn",
      "tactic_smokescreen",
      "summon_wolf",
      "summon_barrier",
      "order_shadow_dive",
      "order_guard_wall",
    ],
    rewardSeed: { gold: 75, dust: 6, gems: 0, accountXp: 5 },
  },
  {
    id: "ladder_bronze_ii_gate_hound",
    name: "Gate Hound",
    leaderId: "leader_aurora",
    squad: ["bran", "mira", "drak"],
    deck: [
      "order_guard_wall",
      "tactic_sanctuary",
      "summon_barrier",
      "order_shadow_dive",
      "order_twin_slash",
      "tactic_battle_hymn",
      "summon_wolf",
      "tactic_smokescreen",
    ],
    rewardSeed: { gold: 75, dust: 6, gems: 0, accountXp: 5 },
  },
  {
    id: "ladder_bronze_ii_thorn_signal",
    name: "Thorn Signal",
    leaderId: "leader_morrow",
    squad: ["vex", "tovi", "kara"],
    deck: [
      "tactic_battle_hymn",
      "tactic_smokescreen",
      "order_focus_fire",
      "order_twin_slash",
      "summon_totem",
      "summon_wolf",
      "order_shadow_dive",
      "order_guard_wall",
    ],
    rewardSeed: { gold: 75, dust: 6, gems: 0, accountXp: 5 },
  },
  {
    id: "ladder_bronze_i_dusk_knight",
    name: "Dusk Knight",
    leaderId: "leader_aurora",
    squad: ["bran", "kara", "mira"],
    deck: [
      "order_guard_wall",
      "order_twin_slash",
      "tactic_sanctuary",
      "order_shadow_dive",
      "tactic_battle_hymn",
      "summon_barrier",
      "summon_totem",
      "tactic_core_burst",
    ],
    rewardSeed: { gold: 90, dust: 8, gems: 0, accountXp: 6 },
  },
  {
    id: "ladder_bronze_i_raven_bannerman",
    name: "Raven Bannerman",
    leaderId: "leader_morrow",
    squad: ["drak", "vex", "tovi"],
    deck: [
      "order_shadow_dive",
      "tactic_smokescreen",
      "order_focus_fire",
      "tactic_battle_hymn",
      "summon_totem",
      "order_twin_slash",
      "summon_wolf",
      "tactic_core_burst",
    ],
    rewardSeed: { gold: 90, dust: 8, gems: 0, accountXp: 6 },
  },
  {
    id: "ladder_bronze_i_oath_ember",
    name: "Oath Ember",
    leaderId: "leader_morrow",
    squad: ["kara", "drak", "bran"],
    deck: [
      "order_twin_slash",
      "order_shadow_dive",
      "tactic_core_burst",
      "tactic_battle_hymn",
      "order_focus_fire",
      "summon_wolf",
      "summon_barrier",
      "tactic_smokescreen",
    ],
    rewardSeed: { gold: 90, dust: 8, gems: 0, accountXp: 6 },
  },
];

export const FRONTLINE_PRESET_BY_ID = Object.fromEntries(
  FRONTLINE_PRESETS.map((entry) => [entry.id, entry]),
);
