import { getHero } from "@/data/heroes";
import type { FrontlineHeroDef } from "./types";

const hero = (heroId: string) => getHero(heroId);

export const FRONTLINE_HEROES: FrontlineHeroDef[] = [
  {
    heroId: "bran",
    name: hero("bran").name,
    role: "Anchor tank",
    family: "hero",
    tier: 3,
    rarity: hero("bran").rarity,
    maxHp: 22,
    atk: 4,
    def: 3,
    speed: 2,
    trait: { type: "bulwark", shield: 3 },
  },
  {
    heroId: "kara",
    name: hero("kara").name,
    role: "Blade striker",
    family: "hero",
    tier: 3,
    rarity: hero("kara").rarity,
    maxHp: 16,
    atk: 7,
    def: 1,
    speed: 5,
    trait: { type: "flurry", atk: 2 },
  },
  {
    heroId: "vex",
    name: hero("vex").name,
    role: "Breach archer",
    family: "hero",
    tier: 3,
    rarity: hero("vex").rarity,
    maxHp: 14,
    atk: 6,
    def: 1,
    speed: 4,
    trait: { type: "breach", extra: 1 },
  },
  {
    heroId: "mira",
    name: hero("mira").name,
    role: "Field healer",
    family: "hero",
    tier: 3,
    rarity: hero("mira").rarity,
    maxHp: 18,
    atk: 4,
    def: 2,
    speed: 3,
    trait: { type: "mend", heal: 3 },
  },
  {
    heroId: "drak",
    name: hero("drak").name,
    role: "Shadow finisher",
    family: "hero",
    tier: 3,
    rarity: hero("drak").rarity,
    maxHp: 15,
    atk: 8,
    def: 1,
    speed: 6,
    trait: { type: "ambush", bonusVsWounded: 2 },
  },
  {
    heroId: "tovi",
    name: hero("tovi").name,
    role: "War chanter",
    family: "hero",
    tier: 3,
    rarity: hero("tovi").rarity,
    maxHp: 17,
    atk: 4,
    def: 2,
    speed: 3,
    trait: { type: "chant", atkAura: 1 },
  },
];

export const FRONTLINE_HERO_BY_ID = Object.fromEntries(
  FRONTLINE_HEROES.map((entry) => [entry.heroId, entry]),
);

export const FRONTLINE_ENEMIES: FrontlineHeroDef[] = [
  {
    heroId: "enemy_bone_archer",
    name: "Bonechitter Archer",
    role: "Skirmish archer",
    family: "enemy",
    tier: 1,
    rarity: "common",
    maxHp: 12,
    atk: 5,
    def: 0,
    speed: 6,
    trait: { type: "breach", extra: 1 },
  },
  {
    heroId: "enemy_rotmaw",
    name: "Rotmaw Ghoul",
    role: "Venom bruiser",
    family: "enemy",
    tier: 1,
    rarity: "common",
    maxHp: 17,
    atk: 6,
    def: 1,
    speed: 4,
    trait: { type: "venom", damage: 2 },
  },
  {
    heroId: "enemy_void_acolyte",
    name: "Void Acolyte",
    role: "Backline chanter",
    family: "enemy",
    tier: 2,
    rarity: "rare",
    maxHp: 15,
    atk: 4,
    def: 1,
    speed: 3,
    trait: { type: "chant", atkAura: 1 },
  },
  {
    heroId: "enemy_plague_troll",
    name: "Plaguebound Troll",
    role: "Slow regenerator",
    family: "enemy",
    tier: 2,
    rarity: "rare",
    maxHp: 25,
    atk: 5,
    def: 3,
    speed: 1,
    trait: { type: "mend", heal: 2 },
  },
  {
    heroId: "enemy_blood_duelist",
    name: "Bloodcourt Duelist",
    role: "Lifesteal duelist",
    family: "enemy",
    tier: 3,
    rarity: "epic",
    maxHp: 16,
    atk: 7,
    def: 1,
    speed: 6,
    trait: { type: "lifesteal", heal: 3 },
  },
  {
    heroId: "enemy_ember_ogre",
    name: "Emberhorn Ogre",
    role: "Siege brute",
    family: "enemy",
    tier: 4,
    rarity: "epic",
    maxHp: 30,
    atk: 8,
    def: 4,
    speed: 1,
    trait: { type: "none" },
  },
];

export const FRONTLINE_ENEMY_BY_ID = Object.fromEntries(
  FRONTLINE_ENEMIES.map((entry) => [entry.heroId, entry]),
);

export const FRONTLINE_UNIT_BY_ID = {
  ...FRONTLINE_HERO_BY_ID,
  ...FRONTLINE_ENEMY_BY_ID,
};
