import type { HomeEffectId } from "@/lib/homeEffectAssets";
import type { HomeLandmarkId } from "@/lib/homeLandmarkAssets";

export type HomeEffectAnchorId = HomeLandmarkId | "world";

export type HomeLandmarkEffectConfig = {
  id: string;
  landmark: HomeEffectAnchorId;
  effect: HomeEffectId;
  xPercent: number;
  yPercent: number;
  widthPercent: number;
  heightPercent: number;
  opacity: number;
  frameCount: number;
  durationMs: number;
  enabled: boolean;
  rotationDeg?: number;
  yawDeg?: number;
  originXPercent?: number;
  originYPercent?: number;
  anchorXPercent?: number;
  anchorYPercent?: number;
  flipX?: boolean;
  flipY?: boolean;
  backgroundY?: string;
  mobileDisabled?: boolean;
};

export function isHomeLandmarkEffectAnchor(anchor: HomeEffectAnchorId): anchor is HomeLandmarkId {
  return anchor !== "world";
}

export const HOME_LANDMARK_EFFECT_DEFS: HomeLandmarkEffectConfig[] = [
  {
    id: "fortress-torch-upper-left",
    landmark: "fortress",
    effect: "flame_loop",
    xPercent: 34.9,
    yPercent: 60.5,
    widthPercent: 9.4,
    heightPercent: 14.3,
    opacity: 1,
    frameCount: 6,
    durationMs: 680,
    enabled: true,
    rotationDeg: 0,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-upper-left-world-copy",
    landmark: "world",
    effect: "flame_loop",
    xPercent: 41.1,
    yPercent: 46.8,
    widthPercent: 2.4,
    heightPercent: 6.7,
    opacity: 1,
    frameCount: 6,
    durationMs: 680,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-upper-left-world-copy-world-copy",
    landmark: "world",
    effect: "flame_loop",
    xPercent: 8.1,
    yPercent: 48,
    widthPercent: 1.5,
    heightPercent: 5.1,
    opacity: 1,
    frameCount: 6,
    durationMs: 680,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-upper-left-world-copy-copy",
    landmark: "world",
    effect: "flame_loop",
    xPercent: 57.3,
    yPercent: 47.2,
    widthPercent: 2.4,
    heightPercent: 6.7,
    opacity: 1,
    frameCount: 6,
    durationMs: 680,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-lower-left",
    landmark: "fortress",
    effect: "flame_loop",
    xPercent: 42.9,
    yPercent: 57,
    widthPercent: 8.7,
    heightPercent: 14.3,
    opacity: 1,
    frameCount: 6,
    durationMs: 730,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-lower-right",
    landmark: "fortress",
    effect: "flame_loop",
    xPercent: 56.5,
    yPercent: 57,
    widthPercent: 8.7,
    heightPercent: 14.3,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-upper-right",
    landmark: "fortress",
    effect: "flame_loop",
    xPercent: 65.3,
    yPercent: 57.2,
    widthPercent: 8.7,
    heightPercent: 14.3,
    opacity: 1,
    frameCount: 6,
    durationMs: 810,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "arena-flag-left",
    landmark: "arena",
    effect: "flag_red_loop",
    xPercent: 25.7,
    yPercent: 71.3,
    widthPercent: 20,
    heightPercent: 30.7,
    opacity: 1,
    frameCount: 5,
    durationMs: 980,
    enabled: true,
    rotationDeg: 0,
    yawDeg: 45,
    flipX: true,
    backgroundY: "52%"
  },
  {
    id: "arena-flag-right",
    landmark: "arena",
    effect: "flag_red_loop",
    xPercent: 75.6,
    yPercent: 72.7,
    widthPercent: 20,
    heightPercent: 30,
    opacity: 1,
    frameCount: 5,
    durationMs: 1100,
    enabled: true,
    yawDeg: -45,
    backgroundY: "52%"
  },
  {
    id: "arena-banner-back-left",
    landmark: "arena",
    effect: "banner_red_loop",
    xPercent: 22.8,
    yPercent: 53.1,
    widthPercent: 14,
    heightPercent: 25,
    opacity: 1,
    frameCount: 6,
    durationMs: 1180,
    enabled: true,
    yawDeg: 25,
    backgroundY: "52%"
  },
  {
    id: "arena-banner-back-right",
    landmark: "arena",
    effect: "banner_red_loop",
    xPercent: 86.3,
    yPercent: 61.3,
    widthPercent: 23.8,
    heightPercent: 68.9,
    opacity: 1,
    frameCount: 6,
    durationMs: 1260,
    enabled: true,
    yawDeg: -25,
    flipX: true,
    backgroundY: "52%"
  },
  {
    id: "arena-banner-back-right-world-copy-2",
    landmark: "world",
    effect: "banner_red_loop",
    xPercent: 69.5,
    yPercent: 33,
    widthPercent: 8.9,
    heightPercent: 27.3,
    opacity: 1,
    frameCount: 6,
    durationMs: 1260,
    enabled: true,
    yawDeg: 163.8,
    originXPercent: 50,
    anchorXPercent: 50,
    anchorYPercent: 50,
    flipX: true,
    flipY: false,
    backgroundY: "52%"
  },
  {
    id: "arena-banner-back-right-world-copy",
    landmark: "world",
    effect: "banner_red_loop",
    xPercent: 56.4,
    yPercent: 27.6,
    widthPercent: 5.8,
    heightPercent: 16.8,
    opacity: 1,
    frameCount: 6,
    durationMs: 1260,
    enabled: true,
    yawDeg: -35.2,
    flipX: true,
    backgroundY: "52%"
  },
  {
    id: "arena-banner-back-right-world-copy-copy",
    landmark: "world",
    effect: "banner_red_loop",
    xPercent: 43.2,
    yPercent: 28.3,
    widthPercent: 6.4,
    heightPercent: 18,
    opacity: 1,
    frameCount: 6,
    durationMs: 1260,
    enabled: true,
    yawDeg: 40,
    flipX: false,
    backgroundY: "52%"
  },
  {
    id: "arena-flag-right-world-copy",
    landmark: "world",
    effect: "flag_red_loop",
    xPercent: 53.4,
    yPercent: 26.9,
    widthPercent: 2,
    heightPercent: 3.3,
    opacity: 1,
    frameCount: 5,
    durationMs: 1100,
    enabled: true,
    originXPercent: 50.2,
    backgroundY: "52%"
  },
  {
    id: "arena-fire-upper-left",
    landmark: "arena",
    effect: "flame_loop",
    xPercent: 31.7,
    yPercent: 51.6,
    widthPercent: 10.8,
    heightPercent: 15.8,
    opacity: 1,
    frameCount: 6,
    durationMs: 640,
    enabled: true,
    backgroundY: "53%"
  },
  {
    id: "arena-fire-upper-right",
    landmark: "arena",
    effect: "flame_loop",
    xPercent: 68.3,
    yPercent: 52.4,
    widthPercent: 10.8,
    heightPercent: 15.8,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "53%"
  },
  {
    id: "arena-fire-lower-left",
    landmark: "arena",
    effect: "flame_loop",
    xPercent: 40.5,
    yPercent: 69.8,
    widthPercent: 8.4,
    heightPercent: 12,
    opacity: 1,
    frameCount: 6,
    durationMs: 700,
    enabled: true,
    backgroundY: "53%"
  },
  {
    id: "arena-fire-lower-right",
    landmark: "arena",
    effect: "flame_loop",
    xPercent: 60.2,
    yPercent: 70.5,
    widthPercent: 8.4,
    heightPercent: 12,
    opacity: 1,
    frameCount: 6,
    durationMs: 740,
    enabled: true,
    backgroundY: "53%"
  },
  {
    id: "adventure-blue-flame-left",
    landmark: "adventure",
    effect: "blue_flame_loop",
    xPercent: 29.1,
    yPercent: 62.5,
    widthPercent: 9.2,
    heightPercent: 14.8,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "adventure-blue-flame-right",
    landmark: "adventure",
    effect: "blue_flame_loop",
    xPercent: 70.5,
    yPercent: 65.2,
    widthPercent: 9.2,
    heightPercent: 14.8,
    opacity: 1,
    frameCount: 6,
    durationMs: 830,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "adventure-blue-flame-right-copy",
    landmark: "adventure",
    effect: "blue_flame_loop",
    xPercent: 89.1,
    yPercent: 60.2,
    widthPercent: 8.7,
    heightPercent: 14,
    opacity: 1,
    frameCount: 6,
    durationMs: 830,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "events-purple-flame-left",
    landmark: "events",
    effect: "purple_flame_loop",
    xPercent: 31.4,
    yPercent: 63.6,
    widthPercent: 9,
    heightPercent: 14,
    opacity: 1,
    frameCount: 6,
    durationMs: 740,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "events-purple-flame-left-world-copy-world-copy",
    landmark: "world",
    effect: "purple_flame_loop",
    xPercent: 23.4,
    yPercent: 74.5,
    widthPercent: 1.5,
    heightPercent: 3.5,
    opacity: 1,
    frameCount: 6,
    durationMs: 740,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "events-purple-flame-left-world-copy-world-copy-copy",
    landmark: "world",
    effect: "purple_flame_loop",
    xPercent: 13.6,
    yPercent: 75.6,
    widthPercent: 1.5,
    heightPercent: 3.5,
    opacity: 1,
    frameCount: 6,
    durationMs: 740,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "events-purple-flame-left-world-copy-world-copy-copy-copy",
    landmark: "world",
    effect: "purple_flame_loop",
    xPercent: 10.5,
    yPercent: 68.6,
    widthPercent: 1.5,
    heightPercent: 3.5,
    opacity: 1,
    frameCount: 6,
    durationMs: 740,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "events-purple-flame-right",
    landmark: "events",
    effect: "purple_flame_loop",
    xPercent: 68.7,
    yPercent: 63.6,
    widthPercent: 9,
    heightPercent: 14,
    opacity: 1,
    frameCount: 6,
    durationMs: 820,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "deck-candle-left",
    landmark: "deck",
    effect: "candle_loop",
    xPercent: 61.3,
    yPercent: 48,
    widthPercent: 4.2,
    heightPercent: 9,
    opacity: 0.95,
    frameCount: 7,
    durationMs: 900,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "deck-candle-left-world-copy-2",
    landmark: "world",
    effect: "candle_loop",
    xPercent: 51.2,
    yPercent: 67.4,
    widthPercent: 0.8,
    heightPercent: 2.2,
    opacity: 0.95,
    frameCount: 7,
    durationMs: 900,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "deck-candle-left-world-copy-2-copy",
    landmark: "world",
    effect: "candle_loop",
    xPercent: 48,
    yPercent: 67.5,
    widthPercent: 0.8,
    heightPercent: 2.2,
    opacity: 0.95,
    frameCount: 7,
    durationMs: 900,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "fortress-torch-upper-left-copy-2",
    landmark: "fortress",
    effect: "flame_loop",
    xPercent: 43.3,
    yPercent: 72.2,
    widthPercent: 7.3,
    heightPercent: 12,
    opacity: 1,
    frameCount: 6,
    durationMs: 680,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-upper-left-copy-2-copy",
    landmark: "fortress",
    effect: "flame_loop",
    xPercent: 56.5,
    yPercent: 73.5,
    widthPercent: 7.3,
    heightPercent: 12,
    opacity: 1,
    frameCount: 6,
    durationMs: 680,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-upper-left-copy",
    landmark: "fortress",
    effect: "flame_loop",
    xPercent: 18.8,
    yPercent: 54,
    widthPercent: 6.3,
    heightPercent: 11.4,
    opacity: 1,
    frameCount: 6,
    durationMs: 680,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "fortress-torch-upper-left-copy-copy",
    landmark: "fortress",
    effect: "flame_loop",
    xPercent: 79.5,
    yPercent: 54.7,
    widthPercent: 6.3,
    heightPercent: 10,
    opacity: 1,
    frameCount: 6,
    durationMs: 680,
    enabled: true,
    backgroundY: "52%",
    mobileDisabled: false
  },
  {
    id: "arena-fire-lower-right-copy",
    landmark: "arena",
    effect: "flame_loop",
    xPercent: 15.8,
    yPercent: 71.3,
    widthPercent: 8.4,
    heightPercent: 12,
    opacity: 1,
    frameCount: 6,
    durationMs: 740,
    enabled: true,
    backgroundY: "53%"
  },
  {
    id: "arena-fire-lower-right-copy-copy",
    landmark: "arena",
    effect: "flame_loop",
    xPercent: 80.7,
    yPercent: 62.4,
    widthPercent: 8.4,
    heightPercent: 12,
    opacity: 1,
    frameCount: 6,
    durationMs: 740,
    enabled: true,
    backgroundY: "53%"
  },
  {
    id: "arena-flag-right-world-copy-copy-2",
    landmark: "world",
    effect: "flag_red_loop",
    xPercent: 55.6,
    yPercent: 28.4,
    widthPercent: 2,
    heightPercent: 3.3,
    opacity: 1,
    frameCount: 5,
    durationMs: 1100,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "arena-flag-right-world-copy-copy",
    landmark: "world",
    effect: "flag_red_loop",
    xPercent: 44.4,
    yPercent: 29.5,
    widthPercent: 2,
    heightPercent: 3.3,
    opacity: 1,
    frameCount: 5,
    durationMs: 1100,
    enabled: true,
    flipX: true,
    flipY: false,
    backgroundY: "52%"
  },
  {
    id: "arena-flag-right-world-copy-copy-copy",
    landmark: "world",
    effect: "flag_red_loop",
    xPercent: 46.6,
    yPercent: 25.8,
    widthPercent: 2,
    heightPercent: 3.3,
    opacity: 1,
    frameCount: 5,
    durationMs: 1100,
    enabled: true,
    flipX: true,
    flipY: false,
    backgroundY: "52%"
  },
  {
    id: "adventure-blue-flame-left-world-copy",
    landmark: "world",
    effect: "blue_flame_loop",
    xPercent: 57.8,
    yPercent: 74.8,
    widthPercent: 2,
    heightPercent: 4,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "adventure-blue-flame-left-world-copy-copy",
    landmark: "world",
    effect: "blue_flame_loop",
    xPercent: 42.3,
    yPercent: 74.4,
    widthPercent: 2,
    heightPercent: 4,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "qa-lantern_warm_loop-copy",
    landmark: "world",
    effect: "lantern_warm_loop",
    xPercent: 72,
    yPercent: 67.2,
    widthPercent: 2,
    heightPercent: 4,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "qa-lantern_warm_loop-copy-world-copy",
    landmark: "world",
    effect: "lantern_warm_loop",
    xPercent: 34.7,
    yPercent: 31,
    widthPercent: 2,
    heightPercent: 4,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "qa-lantern_warm_loop-copy-copy",
    landmark: "world",
    effect: "lantern_warm_loop",
    xPercent: 82.4,
    yPercent: 67.4,
    widthPercent: 1.6,
    heightPercent: 3.4,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "qa-lantern_warm_loop-copy-copy-copy-2",
    landmark: "world",
    effect: "lantern_warm_loop",
    xPercent: 89.6,
    yPercent: 67,
    widthPercent: 1.9,
    heightPercent: 3.8,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "qa-lantern_warm_loop-copy-copy-copy-2-copy",
    landmark: "world",
    effect: "lantern_warm_loop",
    xPercent: 74.4,
    yPercent: 67.8,
    widthPercent: 1.7,
    heightPercent: 3.6,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "qa-lantern_warm_loop-copy-copy-copy-2-copy-copy",
    landmark: "world",
    effect: "lantern_warm_loop",
    xPercent: 75.4,
    yPercent: 74.8,
    widthPercent: 1.7,
    heightPercent: 3.6,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "qa-lantern_warm_loop-copy-copy-copy",
    landmark: "world",
    effect: "lantern_warm_loop",
    xPercent: 85.6,
    yPercent: 67,
    widthPercent: 1.8,
    heightPercent: 3.6,
    opacity: 1,
    frameCount: 6,
    durationMs: 760,
    enabled: true,
    backgroundY: "52%"
  },
  {
    id: "sky-cloud-upper-left",
    landmark: "world",
    effect: "clouds_dark_layer",
    xPercent: 22.5,
    yPercent: 11,
    widthPercent: 43.6,
    heightPercent: 21,
    opacity: 0.55,
    frameCount: 1,
    durationMs: 72000,
    enabled: true,
    backgroundY: "50%",
    mobileDisabled: false
  },
  {
    id: "sky-cloud-upper-mid",
    landmark: "world",
    effect: "clouds_dark_layer",
    xPercent: 36.2,
    yPercent: 13,
    widthPercent: 34,
    heightPercent: 12,
    opacity: 0.5,
    frameCount: 1,
    durationMs: 84000,
    enabled: true,
    flipX: true,
    backgroundY: "50%",
    mobileDisabled: false
  },
  {
    id: "sky-cloud-upper-right",
    landmark: "world",
    effect: "clouds_dark_layer",
    xPercent: 62,
    yPercent: 11.2,
    widthPercent: 41,
    heightPercent: 14,
    opacity: 0.55,
    frameCount: 1,
    durationMs: 68000,
    enabled: true,
    backgroundY: "50%",
    mobileDisabled: false
  },
  {
    id: "sky-cloud-lower-broken",
    landmark: "world",
    effect: "clouds_dark_layer",
    xPercent: 56,
    yPercent: 17.6,
    widthPercent: 29,
    heightPercent: 10,
    opacity: 0.51,
    frameCount: 1,
    durationMs: 76000,
    enabled: true,
    flipX: true,
    backgroundY: "50%",
    mobileDisabled: false
  },
  {
    id: "sky-cloud-lower-broken-copy-2",
    landmark: "world",
    effect: "clouds_dark_layer",
    xPercent: 40.1,
    yPercent: 6.5,
    widthPercent: 29,
    heightPercent: 15.6,
    opacity: 0.55,
    frameCount: 1,
    durationMs: 76000,
    enabled: true,
    flipX: true,
    backgroundY: "50%",
    mobileDisabled: false
  },
  {
    id: "sky-cloud-lower-broken-copy",
    landmark: "world",
    effect: "clouds_dark_layer",
    xPercent: 16,
    yPercent: 8.1,
    widthPercent: 28.6,
    heightPercent: 17.1,
    opacity: 0.5,
    frameCount: 1,
    durationMs: 76000,
    enabled: true,
    flipX: true,
    backgroundY: "50%",
    mobileDisabled: false
  }
];

export function groupHomeLandmarkEffects(effects: HomeLandmarkEffectConfig[]) {
  return effects.reduce<Partial<Record<HomeLandmarkId, HomeLandmarkEffectConfig[]>>>((groups, effect) => {
    if (!effect.enabled || !isHomeLandmarkEffectAnchor(effect.landmark)) return groups;
    groups[effect.landmark] = [...(groups[effect.landmark] ?? []), effect];
    return groups;
  }, {});
}

export function getHomeWorldEffects(effects: HomeLandmarkEffectConfig[]) {
  return effects.filter((effect) => effect.enabled && effect.landmark === "world");
}

export const HOME_LANDMARK_EFFECTS = groupHomeLandmarkEffects(HOME_LANDMARK_EFFECT_DEFS);
export const HOME_WORLD_EFFECTS = getHomeWorldEffects(HOME_LANDMARK_EFFECT_DEFS);
